language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mdesmos/react-test -f ./client/Dockerfile.dev ./client
    

script:
#   - docker run mdesmos/react-test npm test -- --coverage
    - docker run -e CI=true mdesmos/react-test npm test

after_success:
    - docker build - t mdesmos/multi-client ./client
    - docker build - t mdesmos/multi-nginx ./nginx
    - docker build - t mdesmos/multi-server ./server
    - docker build - t mdesmos/multi-worker ./worker
# Log in to the docker CLI
#    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - echo docker login --username "$DOCKER_ID" --password "DOCKER_TOKEN"
# Take those images and push them to docker hub
    - docker push mdesmos/multi-client
    - docker push mdesmos/multi-nginx
    - docker push mdesmos/multi-server
    - docker push mdesmos/multi-worker